player.onChat("Armed", function () {
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    SHIELD,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_SWORD,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_AXE,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_PICKAXE,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    TRIDENT,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_HELMET,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_CHESTPLATE,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_LEGGINGS,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    NETHERITE_BOOTS,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    ENCHANTED_APPLE,
    64
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    TOTEM,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    BOW,
    1
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    ARROW,
    64
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    EMERALD,
    64
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    EXPERIENCE_BOTTLE,
    64
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    ENDER_PEARL,
    16
    )
    mobs.give(
    mobs.target(LOCAL_PLAYER),
    ENDER_EYE,
    64
    )
})
